# Generated by Django 3.2.9 on 2022-07-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('step', models.IntegerField(default=0)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('tel_number', models.CharField(blank=True, max_length=512, null=True)),
                ('active', models.BooleanField(default=False)),
                ('work_experience', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
