# Generated by Django 3.2.9 on 2022-07-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_botuser_cr_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('tel_number', models.CharField(blank=True, max_length=512, null=True)),
                ('active', models.BooleanField(default=False)),
                ('permission', models.CharField(blank=True, max_length=255, null=True)),
                ('cr_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
            ],
        ),
    ]
