# Generated by Django 3.2.9 on 2022-07-27 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_styles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cr_on',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tel_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='bot_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.botuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='employee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
