# Generated by Django 3.2.9 on 2022-08-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_workschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.CharField(max_length=12),
        ),
    ]
