# Generated by Django 3.2.9 on 2022-08-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_messagestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
