# Generated by Django 3.2.9 on 2022-08-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_employee_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
