# Generated by Django 3.2.9 on 2022-08-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220812_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='end_time',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='start_time',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
