# Generated by Django 3.2.9 on 2022-08-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220812_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
